// <auto-generated />
namespace RSGymPT_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class M1Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M1Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "202304161910415_M1Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
